name: Generate uBlacklist filters

on:
  schedule:
    - cron: "7 3 * * *"
  workflow_dispatch:
#  push:
#    branches: [main]
#    paths:
#      - 'list.txt'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Get Latest list.txt from github.com/alvi-se/ai-ublock-blacklist
        run: |
          rm list.txt && wget https://raw.githubusercontent.com/alvi-se/ai-ublock-blacklist/master/list.txt

      - name: Exit workflow if list.txt is unchanged
        run: |
          git diff --cached --quiet && exit 0

      - name: Convert uBlock filters to adguard format
        run: |
          python3 .github/scripts/adguard.py list.txt adguard.txt

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add list.txt adguard.txt
          git commit -m "Update list.txt and auto-generate adguard filters"
          git push

